# 1) HTTP www + sin www -> HTTPS sin www
server {
    listen 80;
    server_name seimor.com www.seimor.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # location / {
    #     return 301 https://seimor.com$request_uri;
    # }
}

# # 2) HTTPS www -> HTTPS sin www
# server {
#     listen 443 ssl;
#     server_name www.seimor.com;

#     ssl_certificate /etc/letsencrypt/live/seimor.com/fullchain.pem;
#     ssl_certificate_key /etc/letsencrypt/live/seimor.com/privkey.pem;
#     ssl_protocols TLSv1.2 TLSv1.3;

#     return 301 https://seimor.com$request_uri;
# }

# # 3) HTTPS sin www -> WordPress.
# ### Antes se debe ejecutar "certbot certonly --webroot -w /var/www/certbot -d seimor.com -d www.seimor.com" con el nuevo subdominio a crear
# server {
#     listen 443 ssl;
#     server_name seimor.com;

#     ssl_certificate /etc/letsencrypt/live/seimor.com/fullchain.pem;
#     ssl_certificate_key /etc/letsencrypt/live/seimor.com/privkey.pem;

#     ssl_protocols TLSv1.2 TLSv1.3;

#     client_max_body_size 64M;

#     # --- Bloqueos de seguridad ---

#     location = /xmlrpc.php {
#         return 403;
#         access_log off;
#     }

#     # Escaneo de archivos sensibles y directorios ocultos
#     location ~ /\. {
#         return 404;
#         access_log off;
#         log_not_found off;
#     }

#     location ~* \.(env|git|gitignore|htaccess|htpasswd|ini|log|sql|bak|backup|swp|old|dist|config)$ {
#         return 404;
#         access_log off;
#         log_not_found off;
#     }

#     location ~* ^/(wp-config\.php|readme\.html|license\.txt|debug\.log) {
#         return 404;
#         access_log off;
#         log_not_found off;
#     }

#     # Enumeración de usuarios (?author=1)
#     if ($arg_author) {
#         return 403;
#     }

#     # --- Proxy con rate limiting ---

#     location = /wp-login.php {
#         limit_req zone=seimor_wp_login burst=10 nodelay;

#         proxy_pass http://seimor:80;

#         proxy_http_version 1.1;

#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#         proxy_set_header X-Forwarded-Host $host;
#         proxy_set_header X-Forwarded-Server $host;
#     }

#     location / {
#         limit_req zone=seimor_general burst=60 nodelay;
#         limit_conn seimor_conn 50;

#         proxy_pass http://seimor:80;

#         proxy_http_version 1.1;

#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#         proxy_set_header X-Forwarded-Host $host;
#         proxy_set_header X-Forwarded-Server $host;
#     }
# }
